### ISSUE TITLE
Aren't these devDependencies ?

### ISSUE THREAD

**Issue by andykenward** [surma/use-workerized-reducer#1]
Aren't the following devDependencies?

 - immer
 - npm-run-all
 - vite

https://github.com/surma/use-workerized-reducer/blob/ee39e9b65a3ad60b94068e2ef447eb565e624982/package.json#L22-L26

Moving them would stop users of the npm package having to install them?

**Comment by andykenward** [comment]
Oh actually `immer` is needed

**Comment by surma** [comment]
Yes, I need to fix that :D

**Comment by andykenward** [comment]
PR https://github.com/surma/use-workerized-reducer/pull/4 closes this issue

**Comment by steida** [comment]
@surma Shouldn't it be released?
